server:
  port: ${PORT:8080}

spring:
  profiles:
    active: test

  thymeleaf:
    cache: false
    mode: HTML
---
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    baseline-on-migrate: true
  config:
    activate:
      on-profile: test
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    baseline-on-migrate: true
  config:
    activate:
      on-profile: dev
